# this is a reusable workflow that rotates the key pair for a snowflake service account
# to reuse, see launch_rotation.yml

name: Rotate Snowflake Credentials

on:
  workflow_call:
    inputs:
      snowflake_service_account:
        description: 'Name of Snowflake Service Account to Rotate'
        required: true
      dbt_cloud_project_id:
        description: 'DBT Cloud Project ID'
        required: true
      passphrase_name:
        description: Name of Azure key vault secret for passphrase
        required: true
      private_key_name:
        description: Azure key vault private key name
        required: true

permissions:
  contents: read
  id-token: write

jobs:
  generate-key-pair:
    # use openssl to generate RSA key pair and store in Github
    runs-on: ubuntu-latest
    outputs:
      snowflake_passphrase: ${{ steps.store_passphrase.outputs.SNOWFLAKE_PASSPHRASE }}
      snowflake_private_key: ${{ steps.store_private_key.outputs.SNOWFLAKE_PRIVATE_KEY }}
      snowflake_public_key: ${{ steps.store_public_key.outputs.SNOWFLAKE_PUBLIC_KEY }}
    steps:
      - name: Store passphrase as GitHub Secret
        id: store_passphrase
        run: |
          echo "::add-mask::$snowflake_passphrase"
          echo "snowflake_passphrase=$(openssl rand -base64 32)" >> $GITHUB_ENV

      - name: Generate RSA key pair
        id: generate_rsa_key
        run: |
        openssl genrsa 2048 | openssl pkcs8 -topk8 -v2 des3 -inform PEM -out rsa_key.p8 -passout pass:${{ env.snowflake_passphrase }}
        openssl rsa -in rsa_key.p8 -pubout -out rsa_key.pub

      - name: Store private key as GitHub Secret
        id: store_private_key
        run: |
          echo "::add-mask::$snowflake_private_key"
          echo "snowflake_private_key=$(cat rsa_key.p8)" >> $GITHUB_ENV

      - name: Store public key as GitHub Secret
        id: store_public_key
        run: |
            echo "::add-mask::$snowflake_public_key"
            echo "snowflake_public_key=$(cat rsa_key.pub | tr -d '\n' | sed 's/-----BEGIN PUBLIC KEY-----//' | sed 's/-----END PUBLIC KEY-----//')" >> $GITHUB_ENV

  rotate-key-pair:
    runs-on: ubuntu-latest
    needs: generate-key-pair
    steps:
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install snowflake-connector-python

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} #https://github.com/Azure/login?tab=readme-ov-file#login-with-a-service-principal-secret

      - name: Get old snowflake passphrase
        id: get_old_passphrase
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: >
            echo "OLD_PASSPHRASE=$(az keyvault secret show
            --vault-name ${{ secrets.AZURE_VAULT_NAME }}
            --name ${{ github.event.inputs.passphrase_name }}
            --query value
            --output tsv)" >> $GITHUB_ENV

      - name: Get old snowflake private key
        id: get_old_private_key
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: >
            az keyvault secret show
            --vault-name ${{ secrets.AZURE_VAULT_NAME }}
            --name ${{ github.event.inputs.private_key_name }}
            --query value
            --output tsv > old_rsa_key.p8

      - name: Rotate Snowflake Service Account Key Pair
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWSQL_PRIVATE_KEY_PASSPHRASE: ${{ env.OLD_PASSPHRASE }}
        run: |
          snowsql -a $SNOWFLAKE_ACCOUNT -u ${{ github.event.inputs.snowflake_service_account }} --private-key-path old_rsa_key.p8 -q "
          ALTER USER ${{ github.event.inputs.snowflake_service_account }} SET RSA_PUBLIC_KEY_2 = RSA_PUBLIC_KEY;
          "
          snowsql -a $SNOWFLAKE_ACCOUNT -u ${{ github.event.inputs.snowflake_service_account }} --private-key-path old_rsa_key.p8 -q "
          ALTER USER ${{ github.event.inputs.snowflake_service_account }} UNSET RSA_PUBLIC_KEY;
          "
          snowsql -a $SNOWFLAKE_ACCOUNT -u ${{ github.event.inputs.snowflake_service_account }} --private-key-path old_rsa_key.p8 -q "
          ALTER USER ${{ github.event.inputs.snowflake_service_account }} SET RSA_PUBLIC_KEY='${{ needs.generate-key-pair.outputs.snowflake_public_key }}';
          "
          snowsql -a $SNOWFLAKE_ACCOUNT -u ${{ github.event.inputs.snowflake_service_account }} --private-key-path old_rsa_key.p8 -q "
          ALTER USER ${{ github.event.inputs.snowflake_service_account }} UNSET RSA_PUBLIC_KEY_2;
          "

  update-azure-kv:
    runs-on: ubuntu-latest
    needs: rotate-key-pair
    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} #https://github.com/Azure/login?tab=readme-ov-file#login-with-a-service-principal-secret

      - name: Upload Key Passphrase to Key Vault
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: >
            az keyvault secret set
            --vault-name ${{ secrets.AZURE_VAULT_NAME }}
            --name ${{ github.event.inputs.passphrase_name }}
            --value "${{ needs.generate-key-pair.outputs.snowflake_passphrase }}"

      - name: Upload RSA Private Key to Key Vault
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: >
            az keyvault secret set
            --vault-name ${{ secrets.AZURE_VAULT_NAME }}
            --name ${{ github.event.inputs.private_key_name }}
            --value "${{ needs.generate-key-pair.outputs.snowflake_private_key }}"

  update-dbt-cloud:
    runs-on: ubuntu-latest
    needs: rotate-key-pair
    env:
      TF_VAR_dbt_account_id: ${{ secrets.DBT_CLOUD_ACCOUNT_ID }}
      TF_VAR_dbt_token: ${{ secrets.DBT_CLOUD_TOKEN }}
      TF_VAR_dbt_host_url: "https://cloud.getdbt.com/api"
      TF_VAR_dbt_project_id: ${{ github.event.inputs.dbt_cloud_project_id }}
      TF_VAR_snowflake_private_key: ${{ needs.generate-key-pair.outputs.snowflake_private_key }}
      TF_VAR_snowflake_passphrase: ${{ needs.generate-key-pair.outputs.snowflake_passphrase }}
      TF_VAR_snowflake_service_account: ${{ github.event.inputs.snowflake_service_account }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0  # Specify your Terraform version

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Apply Terraform Changes
        run: terraform apply -auto-approve tfplan